<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Product;
use App\Models\Category;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Get categories by slug
        $categories = Category::all()->keyBy('slug');

        $products = [
            // Chairs
            [
                'name' => 'Boho Macrame Hanging Chair',
                'description' => 'Beautiful handcrafted macrame hanging chair perfect for indoor and outdoor use. Made with premium cotton rope and sturdy metal frame.',
                'category' => 'CHAIRS',
                'category_slug' => 'chairs',
                'price' => 299.99,
                'original_price' => 399.99,
                'discount_percentage' => 25,
                'rating' => 4.8,
                'reviews_count' => 127,
                'image' => 'images/green_sofa_hero.png',
                'stock' => 15,
                'is_featured' => true,
                'is_new_arrival' => true,
                'is_best_seller' => true,
            ],
            [
                'name' => 'Woven Accent Chair',
                'description' => 'Stylish woven accent chair with natural fibers. Perfect for reading nooks and bedrooms.',
                'category' => 'CHAIRS',
                'category_slug' => 'chairs',
                'price' => 249.99,
                'original_price' => 329.99,
                'discount_percentage' => 24,
                'rating' => 4.6,
                'reviews_count' => 89,
                'image' => 'images/green_sofa_hero.png',
                'stock' => 22,
                'is_featured' => false,
                'is_new_arrival' => true,
                'is_best_seller' => false,
            ],
            [
                'name' => 'Leather Butterfly Chair',
                'description' => 'Classic butterfly chair with genuine leather seat and metal frame. Iconic mid-century design.',
                'category' => 'CHAIRS',
                'category_slug' => 'chairs',
                'price' => 379.99,
                'original_price' => null,
                'discount_percentage' => 0,
                'rating' => 4.9,
                'reviews_count' => 156,
                'image' => 'images/green_sofa_hero.png',
                'stock' => 8,
                'is_featured' => true,
                'is_new_arrival' => false,
                'is_best_seller' => true,
            ],
            [
                'name' => 'Rattan Peacock Chair',
                'description' => 'Iconic rattan peacock chair with fan-shaped back. Statement piece for any room.',
                'category' => 'CHAIRS',
                'category_slug' => 'chairs',
                'price' => 549.99,
                'original_price' => 699.99,
                'discount_percentage' => 21,
                'rating' => 5.0,
                'reviews_count' => 203,
                'image' => 'images/green_sofa_hero.png',
                'stock' => 5,
                'is_featured' => true,
                'is_new_arrival' => false,
                'is_best_seller' => true,
            ],

            // Sofas
            [
                'name' => 'Vintage Rattan Sofa',
                'description' => 'Elegant vintage-style rattan sofa with comfortable cushions. Perfect for living rooms and sunrooms.',
                'category' => 'SOFAS',
                'category_slug' => 'sofas',
                'price' => 899.99,
                'original_price' => 1199.99,
                'discount_percentage' => 25,
                'rating' => 4.7,
                'reviews_count' => 178,
                'image' => 'images/green_sofa_hero.png',
                'stock' => 12,
                'is_featured' => true,
                'is_new_arrival' => true,
                'is_best_seller' => true,
            ],
            [
                'name' => 'Velvet Lounge Sofa',
                'description' => 'Luxurious velvet lounge sofa in forest green. Deep seating with plush cushions.',
                'category' => 'SOFAS',
                'category_slug' => 'sofas',
                'price' => 1499.99,
                'original_price' => 1899.99,
                'discount_percentage' => 21,
                'rating' => 4.9,
                'reviews_count' => 245,
                'image' => 'images/green_sofa_hero.png',
                'stock' => 6,
                'is_featured' => true,
                'is_new_arrival' => true,
                'is_best_seller' => true,
            ],
            [
                'name' => 'Sectional L-Shaped Sofa',
                'description' => 'Spacious L-shaped sectional sofa with chaise lounge. Seats 6-7 people comfortably.',
                'category' => 'SOFAS',
                'category_slug' => 'sofas',
                'price' => 1899.99,
                'original_price' => null,
                'discount_percentage' => 0,
                'rating' => 4.8,
                'reviews_count' => 312,
                'image' => 'images/green_sofa_hero.png',
                'stock' => 4,
                'is_featured' => true,
                'is_new_arrival' => false,
                'is_best_seller' => true,
            ],

            // Tables
            [
                'name' => 'Bamboo Coffee Table',
                'description' => 'Sustainable bamboo coffee table with modern design. Eco-friendly and durable.',
                'category' => 'TABLES',
                'category_slug' => 'tables',
                'price' => 349.99,
                'original_price' => 449.99,
                'discount_percentage' => 22,
                'rating' => 4.5,
                'reviews_count' => 98,
                'image' => 'images/green_sofa_hero.png',
                'stock' => 18,
                'is_featured' => false,
                'is_new_arrival' => true,
                'is_best_seller' => false,
            ],
            [
                'name' => 'Teak Wood Dining Table',
                'description' => 'Solid teak wood dining table seats 6-8 people. Timeless design with natural finish.',
                'category' => 'TABLES',
                'category_slug' => 'tables',
                'price' => 1299.99,
                'original_price' => 1599.99,
                'discount_percentage' => 19,
                'rating' => 4.9,
                'reviews_count' => 267,
                'image' => 'images/green_sofa_hero.png',
                'stock' => 7,
                'is_featured' => true,
                'is_new_arrival' => false,
                'is_best_seller' => true,
            ],
            [
                'name' => 'Rustic Wooden Bookshelf',
                'description' => 'Five-tier rustic wooden bookshelf with natural finish. Perfect for displaying books and decor.',
                'category' => 'TABLES',
                'category_slug' => 'tables',
                'price' => 429.99,
                'original_price' => null,
                'discount_percentage' => 0,
                'rating' => 4.6,
                'reviews_count' => 134,
                'image' => 'images/green_sofa_hero.png',
                'stock' => 14,
                'is_featured' => false,
                'is_new_arrival' => true,
                'is_best_seller' => false,
            ],
            [
                'name' => 'Carved Wooden Side Table',
                'description' => 'Hand-carved wooden side table with intricate patterns. Perfect as a nightstand or accent piece.',
                'category' => 'TABLES',
                'category_slug' => 'tables',
                'price' => 189.99,
                'original_price' => 249.99,
                'discount_percentage' => 24,
                'rating' => 4.7,
                'reviews_count' => 176,
                'image' => 'images/green_sofa_hero.png',
                'stock' => 25,
                'is_featured' => false,
                'is_new_arrival' => true,
                'is_best_seller' => true,
            ],
            [
                'name' => 'Minimalist Console Table',
                'description' => 'Sleek minimalist console table with marble top and metal frame. Modern elegance.',
                'category' => 'TABLES',
                'category_slug' => 'tables',
                'price' => 599.99,
                'original_price' => 799.99,
                'discount_percentage' => 25,
                'rating' => 4.8,
                'reviews_count' => 189,
                'image' => 'images/green_sofa_hero.png',
                'stock' => 10,
                'is_featured' => true,
                'is_new_arrival' => true,
                'is_best_seller' => false,
            ],

            // Ottomans
            [
                'name' => 'Moroccan Pouf Ottoman',
                'description' => 'Authentic Moroccan pouf ottoman with intricate embroidery. Adds a touch of bohemian style to any room.',
                'category' => 'OTTOMANS',
                'category_slug' => 'ottomans',
                'price' => 149.99,
                'original_price' => 199.99,
                'discount_percentage' => 25,
                'rating' => 4.6,
                'reviews_count' => 145,
                'image' => 'images/green_sofa_hero.png',
                'stock' => 30,
                'is_featured' => false,
                'is_new_arrival' => true,
                'is_best_seller' => true,
            ],
            [
                'name' => 'Velvet Ottoman Bench',
                'description' => 'Luxurious velvet ottoman bench with gold metal legs. Perfect for bedroom or entryway.',
                'category' => 'OTTOMANS',
                'category_slug' => 'ottomans',
                'price' => 279.99,
                'original_price' => null,
                'discount_percentage' => 0,
                'rating' => 4.8,
                'reviews_count' => 198,
                'image' => 'images/green_sofa_hero.png',
                'stock' => 16,
                'is_featured' => true,
                'is_new_arrival' => false,
                'is_best_seller' => true,
            ],
            [
                'name' => 'Wicker Storage Ottoman',
                'description' => 'Wicker storage ottoman with lift-top lid. Functional and stylish storage solution.',
                'category' => 'OTTOMANS',
                'category_slug' => 'ottomans',
                'price' => 169.99,
                'original_price' => 219.99,
                'discount_percentage' => 23,
                'rating' => 4.5,
                'reviews_count' => 112,
                'image' => 'images/green_sofa_hero.png',
                'stock' => 20,
                'is_featured' => false,
                'is_new_arrival' => true,
                'is_best_seller' => false,
            ],

            // Accessories
            [
                'name' => 'Rattan Storage Basket Set',
                'description' => 'Set of 3 handwoven rattan storage baskets. Perfect for organizing and decoration.',
                'category' => 'ACCESSORIES',
                'category_slug' => 'accessories',
                'price' => 79.99,
                'original_price' => 99.99,
                'discount_percentage' => 20,
                'rating' => 4.7,
                'reviews_count' => 234,
                'image' => 'images/green_sofa_hero.png',
                'stock' => 45,
                'is_featured' => false,
                'is_new_arrival' => true,
                'is_best_seller' => true,
            ],
            [
                'name' => 'Bohemian Floor Cushions',
                'description' => 'Set of 4 colorful bohemian floor cushions with tassels. Great for meditation or extra seating.',
                'category' => 'ACCESSORIES',
                'category_slug' => 'accessories',
                'price' => 129.99,
                'original_price' => null,
                'discount_percentage' => 0,
                'rating' => 4.6,
                'reviews_count' => 167,
                'image' => 'images/green_sofa_hero.png',
                'stock' => 28,
                'is_featured' => false,
                'is_new_arrival' => true,
                'is_best_seller' => false,
            ],
            [
                'name' => 'Jute Area Rug',
                'description' => 'Natural jute area rug 8x10 feet. Eco-friendly and durable for high-traffic areas.',
                'category' => 'ACCESSORIES',
                'category_slug' => 'accessories',
                'price' => 199.99,
                'original_price' => 259.99,
                'discount_percentage' => 23,
                'rating' => 4.8,
                'reviews_count' => 289,
                'image' => 'images/green_sofa_hero.png',
                'stock' => 19,
                'is_featured' => true,
                'is_new_arrival' => false,
                'is_best_seller' => true,
            ],
            [
                'name' => 'Macrame Wall Hanging',
                'description' => 'Large macrame wall hanging with geometric patterns. Handmade bohemian wall art.',
                'category' => 'ACCESSORIES',
                'category_slug' => 'accessories',
                'price' => 89.99,
                'original_price' => 119.99,
                'discount_percentage' => 25,
                'rating' => 4.9,
                'reviews_count' => 312,
                'image' => 'images/green_sofa_hero.png',
                'stock' => 35,
                'is_featured' => false,
                'is_new_arrival' => true,
                'is_best_seller' => true,
            ],
            [
                'name' => 'Ceramic Garden Stool',
                'description' => 'Decorative ceramic garden stool with floral pattern. Use as side table or extra seating.',
                'category' => 'ACCESSORIES',
                'category_slug' => 'accessories',
                'price' => 139.99,
                'original_price' => null,
                'discount_percentage' => 0,
                'rating' => 4.7,
                'reviews_count' => 201,
                'image' => 'images/green_sofa_hero.png',
                'stock' => 12,
                'is_featured' => true,
                'is_new_arrival' => false,
                'is_best_seller' => false,
            ],
        ];

        foreach ($products as $productData) {
            // Get category slug and remove it from product data
            $categorySlug = $productData['category_slug'];
            unset($productData['category_slug']);
            unset($productData['category']); // Remove category string field

            // Assign category_id
            if (isset($categories[$categorySlug])) {
                $productData['category_id'] = $categories[$categorySlug]->id;
            }

            Product::create($productData);
        }
    }
}
